classdef tdocconvert < tDocMaker
    %TDOCCONVERT Tests for docconvert.

    methods ( Test )

        function tConversionProducesHTMLFile( testCase )

            output = docconvert( testCase.ExampleFile, ...
                "Root", testCase.Folder );
            testCase.verifyTrue( isfile( output ), ...
                "docconvert failed to produce a file." )

            [~, ~, ext] = fileparts( output );
            testCase.verifyEqual( ext, ".html", ...
                "docconvert failed to produce an HTML document." )

        end % tConversionProducesHTMLFile

        function tLaTeXConversionProducesCorrectHTMLFile( testCase )

            output = docconvert( testCase.ExampleLaTeXFile, ...
                "Root", testCase.Folder, ...
                "Interpreter", "latex", ...
                "MathRenderer", "GitHub" );
            testCase.verifyTrue( isfile( output ), ...
                "docconvert failed to produce a file from a " + ...
                "Markdown file containing LaTeX." )
            [~, ~, ext] = fileparts( output );
            testCase.verifyEqual( ext, ".html", ...
                "docconvert failed to produce an HTML document " + ...
                "from a Markdown file containing LaTeX." )

            raw = readlines( output );
            testCase.verifyEqual( raw(2), ...
                "<p>$ \sin^2x + \cos^2x = 1 $</p>", ...
                "docconvert did not convert inline LaTeX correctly." )
            testCase.verifyEqual( raw(3), ...
                "<p>$$ \int_{-\infty}^\infty f(x) dx = 1 $$</p>", ...
                "docconvert did not convert display LaTeX correctly." )
            testCase.verifyTrue( startsWith( raw(4), ...
                "<p>$$ \Phi = \frac{\dot{m}_{th} + " + ...
                "\dot{m}}{2} ht_{in} - \frac{\dot{m}_{th} - " + ...
                "\dot{m}}{2} ht_{out} $$</p>" ), ...
                "docconvert did not convert display LaTeX correctly." )

        end % tLaTeXConversionProducesCorrectHTMLFile
        
    end % methods ( Test )

end % classdef