classdef tdocdelete < tDocMaker
    %TDOCDELETE Tests for docdelete.

    methods ( Test )

        function tDeletionIsWarningFree( testCase )

            deleter = @() docdelete( testCase.Folder );
            testCase.fatalAssertWarningFree( deleter, ...
                "docdelete was not warning-free when called on a" + ...
                " temporary folder." )

        end % tDeletionIsWarningFree

        function tFilesAreRemovedAfterConversion( testCase )

            docconvert( testCase.ExampleFile, "Root", testCase.Folder )
            [removedFiles, removedFolders] = docdelete( testCase.Folder );
            testCase.verifyEqual( removedFiles, ...
                fullfile( testCase.Folder, "Example.html" ), ...
                "docdelete did not delete the example HTML file." )
            testCase.verifyEqual( removedFolders, ...
                fullfile( testCase.Folder, "resources" ), ...
                "docdelete did not delete the resources folder." )

        end % tFilesAreRemovedAfterConversion

        function tFilesAreRemovedAfterConversionAndRunning( testCase )

            outputFiles = docconvert( testCase.ExampleFile, ...
                "Root", testCase.Folder );
            docrun( outputFiles )
            [removedFiles, removedFolders] = docdelete( testCase.Folder );
            testCase.verifyEqual( removedFiles, ...
                fullfile( testCase.Folder, "Example.html" ), ...
                "docdelete did not delete the example HTML file." )
            testCase.verifyEqual( removedFolders, ...
                fullfile( testCase.Folder, "resources" ), ...
                "docdelete did not delete the resources folder." )

        end % tFilesAreRemovedAfterConversionAndRunning

        function tFilesAreRemovedAfterCompleteBuild( testCase )

            outputFiles = docconvert( testCase.ExampleFile, ...
                "Root", testCase.Folder );
            docrun( outputFiles )
            docindex( testCase.Folder )
            [removedFiles, removedFolders] = docdelete( testCase.Folder );
            testCase.verifyEqual( removedFiles(1), ...
                fullfile( testCase.Folder, "Example.html" ), ...
                "docdelete did not delete the example HTML file." )
            testCase.verifyEqual( removedFiles(2), ...
                fullfile( testCase.Folder, "info.xml" ), ...
                "docdelete did not delete info.xml." )
            testCase.verifyEqual( removedFiles(3), ...
                fullfile( testCase.Folder, "helptoc.xml" ), ...
                "docdelete did not delete helptoc.xml." )
            testCase.verifyEqual( removedFolders(1), ...
                fullfile( testCase.Folder, "resources" ), ...
                "docdelete did not delete the resources folder." )
            testCase.verifyEqual( removedFolders(2), ...
                fullfile( testCase.Folder, "helpsearch-v4_en" ), ...
                "docdelete did not delete the " + ...
                "documentation search database." )

        end % tFilesAreRemovedAfterCompleteBuild

    end % methods ( Test )

end % classdef