classdef tGitLab < matlab.unittest.TestCase
    %TGITLAB Tests for GitLab Markdown conversion helpers.

    methods ( Test )

        function tCleanGitLabImagesUsesDataSource( testCase )

            doc = parseXml( "<div><img " + ...
                "src=""data:image/gif;base64,abc"" " + ...
                "alt=""Cluster State"" decoding=""async"" " + ...
                "class=""lazy"" " + ...
                "data-src=""images/ImageTest.png""/></div>" );

            docmaker.cleanGitLabImages( doc )

            img = doc.getElementsByTagName( "img" ).item( 0 );
            testCase.verifyEqual( ...
                string( img.getAttribute( "src" ) ), ...
                "images/ImageTest.png", ...
                "GitLab data-src was not promoted to src." )
            testCase.verifyFalse( img.hasAttribute( "data-src" ), ...
                "GitLab data-src attribute was not removed." )
            testCase.verifyFalse( img.hasAttribute( "class" ), ...
                "GitLab lazy class was not removed." )
            testCase.verifyFalse( img.hasAttribute( "decoding" ), ...
                "GitLab async decoding attribute was not removed." )

        end % tCleanGitLabImagesUsesDataSource

        function tCleanGitLabImagesPreservesOtherAttributes( testCase )

            doc = parseXml( "<div><img " + ...
                "src=""data:image/gif;base64,abc"" " + ...
                "alt=""Cluster State"" " + ...
                "data-sourcepos=""1:1-1:39"" " + ...
                "class=""lazy border"" " + ...
                "data-src=""images/ImageTest.png""/></div>" );

            docmaker.cleanGitLabImages( doc )

            img = doc.getElementsByTagName( "img" ).item( 0 );
            testCase.verifyEqual( ...
                string( img.getAttribute( "class" ) ), "border", ...
                "Non-lazy image classes were not preserved." )
            testCase.verifyEqual( ...
                string( img.getAttribute( "alt" ) ), "Cluster State", ...
                "Image alt text was not preserved." )
            testCase.verifyEqual( ...
                string( img.getAttribute( "data-sourcepos" ) ), ...
                "1:1-1:39", ...
                "GitLab source position metadata was not preserved." )

        end % tCleanGitLabImagesPreservesOtherAttributes

        function tGitLabImageFixtureIsRenderable( testCase )

            markdownFile = fullfile( fixtureFolder(), "ImageTest.md" );
            markdown = string( fileread( markdownFile ) );
            testCase.verifyTrue( contains( markdown, ...
                "![Cluster State](ImageTest.png)" ), ...
                "The GitLab image bug fixture lost its image reference." )

            doc = parseXml( "<div><p data-sourcepos=""1:1-1:39"" " + ...
                "dir=""auto""><a class=""no-attachment-icon"" " + ...
                "href=""ImageTest.png"" target=""_blank"" " + ...
                "rel=""noopener noreferrer""><img " + ...
                "data-sourcepos=""1:1-1:39"" " + ...
                "src=""data:image/gif;base64,abc"" " + ...
                "alt=""Cluster State"" decoding=""async"" " + ...
                "class=""lazy"" " + ...
                "data-src=""ImageTest.png""/></a></p></div>" );

            docmaker.cleanGitLabImages( doc )

            img = doc.getElementsByTagName( "img" ).item( 0 );
            testCase.verifyEqual( ...
                string( img.getAttribute( "src" ) ), ...
                "ImageTest.png", ...
                "Cleaned GitLab image output should be renderable." )
            testCase.verifyFalse( img.hasAttribute( "data-src" ), ...
                "Cleaned GitLab image output should not use data-src." )
            testCase.verifyFalse( img.hasAttribute( "class" ), ...
                "Cleaned GitLab image output should not keep lazy class." )
            testCase.verifyFalse( img.hasAttribute( "decoding" ), ...
                "Cleaned GitLab image output should not keep decoding." )

        end % tGitLabImageFixtureIsRenderable

    end % methods ( Test )

end % classdef

function folder = fixtureFolder()
%fixtureFolder  Location of the GitLab image bug fixture

folder = fileparts( mfilename( "fullpath" ) );

end % fixtureFolder

function doc = parseXml( xml )
%parseXml  Parse an XML string into a DOM document

parser = matlab.io.xml.dom.Parser();
doc = parser.parseString( xml );

end % parseXml
