function html = md2html( nMd, nCss )

% Handle inputs
[pMd, fMd, ~] = fileparts( nMd );
nHtml = fullfile( pMd, [fMd '.html'] );

% Read input
md = fileread( nMd );

% Convert
htmlf = markdowndoc.md2htmlf( md );

% Wrap
html = "<!DOCTYPE html>" + newline + ...
    "<html xmlns=""http://www.w3.org/1999/xhtml"" xml:lang=""en"" lang=""en"">" + newline + ...
    "<head>" + newline + ...
    "<title>" + fMd + "</title>" + newline + ...
    "<link rel=""stylesheet"" href=""" + nCss + """>" + newline + ...
    "<script src=""lazyload.js""></script>" + newline + ...
    "</head>" + newline + ...
    "<body>" + newline + "<main>" + newline + ...
    htmlf + newline + ...
    "</main>" + newline + "</body>" + newline + ...
    "</html>";

% Write output
fHtml = fopen( nHtml, "w+" );
fprintf( fHtml, "%s", html );
fclose( fHtml );

end % md2html