function h = htmlify( t, b )

h = "<!DOCTYPE html>" + newline + ...
    "<html xmlns=""http://www.w3.org/1999/xhtml"" xml:lang=""en"" lang=""en"">" + newline + ...
    "<head><title>" + t + "</title></head>" + newline + ...
    "<body>" + newline + b + newline + "</body>" + newline + "</html>";

end